sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
cache:
  directores:
    - $HOME/.gradle
    - .gradle
script:
  - ./gradlew build
  - ./gradlew javadoc
notifications:
  on_failure: change # always|never
on_success: never
